mod_id                             = imaginarycraft
mod_name                           = ImaginaryCraft
mod_license                        = OSL v3.0
mod_version                        = 1.0.0
mod_group_id                       = architecture.imaginarycraft
mod_authors                        = Architecture
mod_description                    =

